[package]
edition = "2021"
name = "pyo3_evcxr"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.109"
pyo3.default-features = false
pyo3.features = ["auto-initialize"]
pyo3.version = "0.15.1"
